// flow-typed signature: 19b87083873bc8ec0aabfb4ced3eb508
// flow-typed version: <<STUB>>/jsonapi-client_vhttps://github.com/holidayextras/jsonapi-client#0.8.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonapi-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonapi-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonapi-client/karma.local.conf' {
  declare module.exports: any;
}

declare module 'jsonapi-client/karma.saucelabs.conf' {
  declare module.exports: any;
}

declare module 'jsonapi-client/lib/Client' {
  declare module.exports: any;
}

declare module 'jsonapi-client/lib/Resource' {
  declare module.exports: any;
}

declare module 'jsonapi-client/lib/resourceCache' {
  declare module.exports: any;
}

declare module 'jsonapi-client/lib/Transport' {
  declare module.exports: any;
}

declare module 'jsonapi-client/test/_testServer' {
  declare module.exports: any;
}

declare module 'jsonapi-client/test/authentication' {
  declare module.exports: any;
}

declare module 'jsonapi-client/test/promises' {
  declare module.exports: any;
}

declare module 'jsonapi-client/test/read' {
  declare module.exports: any;
}

declare module 'jsonapi-client/test/write' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonapi-client/karma.local.conf.js' {
  declare module.exports: $Exports<'jsonapi-client/karma.local.conf'>;
}
declare module 'jsonapi-client/karma.saucelabs.conf.js' {
  declare module.exports: $Exports<'jsonapi-client/karma.saucelabs.conf'>;
}
declare module 'jsonapi-client/lib/Client.js' {
  declare module.exports: $Exports<'jsonapi-client/lib/Client'>;
}
declare module 'jsonapi-client/lib/Resource.js' {
  declare module.exports: $Exports<'jsonapi-client/lib/Resource'>;
}
declare module 'jsonapi-client/lib/resourceCache.js' {
  declare module.exports: $Exports<'jsonapi-client/lib/resourceCache'>;
}
declare module 'jsonapi-client/lib/Transport.js' {
  declare module.exports: $Exports<'jsonapi-client/lib/Transport'>;
}
declare module 'jsonapi-client/test/_testServer.js' {
  declare module.exports: $Exports<'jsonapi-client/test/_testServer'>;
}
declare module 'jsonapi-client/test/authentication.js' {
  declare module.exports: $Exports<'jsonapi-client/test/authentication'>;
}
declare module 'jsonapi-client/test/promises.js' {
  declare module.exports: $Exports<'jsonapi-client/test/promises'>;
}
declare module 'jsonapi-client/test/read.js' {
  declare module.exports: $Exports<'jsonapi-client/test/read'>;
}
declare module 'jsonapi-client/test/write.js' {
  declare module.exports: $Exports<'jsonapi-client/test/write'>;
}
